### ISSUE TITLE
expire so soon

### ISSUE THREAD

**Issue by daniel-lo** [iobroker-community-adapters/ioBroker.fitbit-api#27]
Just got my tokens .. but I wonder why expiry is already this afternoon?

Also I get a warning that they are written without an ack-flag.

**Comment by Apollon77** [comment]
Please provide logs

**Comment by Apollon77** [comment]
PS: Tokens are usually refereshed automatically

**Comment by daniel-lo** [comment]
zu lange her .. jetzt sehe ich sowas hier beim öffnen der Setting-Seite:

![grafik](https://user-images.githubusercontent.com/4311558/158031527-ab4ff7a0-a1cf-4a8e-a4b3-90a25eefd704.png)

**Comment by Apollon77** [comment]
Please try to install GitHub version ... (updated some mins ago): WHat the error shows then?

**Comment by daniel-lo** [comment]
Bis auf verrutschter Text das gleiche:

![grafik](https://user-images.githubusercontent.com/4311558/158047447-8108300d-18b5-4059-9654-3124f15ad368.png)

**Comment by Apollon77** [comment]
Wann komt die Meldung denn? Habs gestern selbst versucht ... beimir tut alles ohne diese Meldung ... Das generelle Problem gerade ist aber das es im Chrome im Iframe nicht mehr tut ... FF geht bei mir - wenn ich mch vorher einlogge

**Comment by daniel-lo** [comment]
Benutze FF .. was meinst Du mit vorher einloggen? Hab den Adapter am laufen .. und will mir die Adapterconf anschauen .. dann Meldung

**Comment by Apollon77** [comment]
Die Meldung kommt direkt wenn Du die Adapter-Konfig öffnest?

**Comment by daniel-lo** [comment]
si

**Comment by Apollon77** [comment]
Welche Admin version?

**Comment by daniel-lo** [comment]
Hab das schon länger .. inzwischen so einige admins .. jetzt grad 5.3.1

**Comment by Apollon77** [comment]
kann ich ncht nachvollziehen ... müsste man mit Debugger ran :-(

**Comment by daniel-lo** [comment]
ich soll debugging anschalten?

**Comment by Apollon77** [comment]
Ne da muss man im Brower debuggen wo diese Meldung herkommt und was es ist ...  Passiert es nur bei dem Adapter?

**Comment by daniel-lo** [comment]
ja .. nur der

**Comment by Apollon77** [comment]
Jetzt remote ... steht denn in der browser Fehlerkonsole irgendwas wenn die meldung kommt?

**Comment by daniel-lo** [comment]
hätte schon längst geantwortet .. komme aber seit vorhin nicht mehr ran .. host not found .. no compact mode .. bla bla .. fängt sich dann irgendwann .. hab auch schon alle zaubertricks probiert .. melde mich wenn sich der kollege wieder beruhigt

**Comment by Apollon77** [comment]
Whhaatt??? Then I would strt (forum) to check your system because it might be related :-)

**Comment by daniel-lo** [comment]
Hab ich doch schon ewigkeiten .. eine Zeit lang lief es jetzt prima .. die Tage spackt es wieder .. für mich nichts Neues

**Comment by daniel-lo** [comment]
Hab jetzt ein Rollback gemacht .. JS-Adapter lief nicht mehr .. hier der screenshot vom terminal .. hoffe das war es was du benötigst:

![grafik](https://user-images.githubusercontent.com/4311558/158243676-df497d06-0f49-45ba-90ed-d31e742e962e.png)

**Comment by Apollon77** [comment]
Vllt solltest u mal die instanz löschen und neu einrichten (oder die keys löschen und neu einrichten)

**Comment by daniel-lo** [comment]
bin der Meinung hätte ich alles schonmal gemacht .. kann ich nochmal machen

**Comment by daniel-lo** [comment]
heute krieg ich auch dies hier ...

<html><body>


fitbit-api.0 | 2022-03-15 04:30:05.830 | error | Cannot  get new token:  {"errors":[{"errorType":"invalid_grant","message":"Refresh token  invalid:  89fcac26d7f174d4fc47d8ecee52d81bcbb954a2b670cdc80b8908cc9bbff63a. Visit  https://dev.fitbit.com/docs/oauth2 for more information on the Fitbit  Web API authorization process."}],"success":false}
-- | -- | -- | --



</body>
</html>

**Comment by Apollon77** [comment]
When you get this? After having reset the tokens?

**Comment by daniel-lo** [comment]
Didn't do anything .. just a rollback to two days ago. But not aware of any changes since then.

**Comment by Apollon77** [comment]
Hm .. yes a rollback might get you "Old" refresh token which is no longer valid ... you need to get new ones

**Comment by daniel-lo** [comment]
ok .. that should explain that error .. thanks .. still getting this popup though

**Comment by daniel-lo** [comment]
Oje oje ... 

<html><body>


fitbit-api.0 | 2022-03-16 19:45:05.761 | error | Cannot  get new token:  {"errors":[{"errorType":"invalid_grant","message":"Refresh token  invalid:  89fcac26d7f174d4fc47d8ecee52d81bcbb954a2b670cdc80b8908cc9bbff63a. Visit  https://dev.fitbit.com/docs/oauth2 for more information on the Fitbit  Web API authorization process."}],"success":false}
-- | -- | -- | --
fitbit-api.0 | 2022-03-16 19:45:05.759 | error | Cannot  get new token:  {"errors":[{"errorType":"invalid_grant","message":"Refresh token  invalid:  89fcac26d7f174d4fc47d8ecee52d81bcbb954a2b670cdc80b8908cc9bbff63a. Visit  https://dev.fitbit.com/docs/oauth2 for more information on the Fitbit  Web API authorization process."}],"success":false}


</body>
</html>

**Comment by Apollon77** [comment]
Also nach holen vom neuen token schon wieder der fehler oder wie? Und zwischen drin tat es?

**Comment by daniel-lo** [comment]
Komme langsam durcheinander. Die letzte Maildung besagt doch, dass er kein neues Token holen konte?!

**Comment by Apollon77** [comment]
Jetzt mal bitte langsam: Die Meldung sagt er kann das Refresh Toke nicht nutzen um automatisch das Token zu aktualisieren ... daher habe ich gesagt -... du musst bitte genrrell einmal neu "einloggen" das du generell neue tokens bekommst. Danach sollte auch der refresh wieder gehen

**Comment by daniel-lo** [comment]
https://youtu.be/S5lSqFTnUyY

geht leider nicht

**Comment by Apollon77** [comment]
Video privat, kann ich  nicht sehen

**Comment by daniel-lo** [comment]
probier mal bitte nochmal .. hab auf - nicht gelistet gestellt .. erstes mal dass ich YT dafür verwende

**Comment by daniel-lo** [comment]
Ist wohl ein FF Problem

**Comment by Apollon77** [comment]
Ich dachte da Thema hatten wir schon in nem anderen issue geklärt??

Im Forefix musst du  bei der "darf nicht im iframe" fehler auf "open in new window" klicken, dann dort einloggen. Danach Adapter Konfig schliessen und direkt neu auf machen, Button nochmal drüben ... dann ist was im fenster an sich.

UND wegen dem Fehler dialog hab ich dir gesgat du sollst die GitHub version installieren weil ich da versucht habe das die Meldung richtig kommt ... Das hast du nicht getan oder Install war nicht erfolgreich ... Hatten wir ehrlicvh auch bei anderen adaptern schonmal das Du gesagt hast das Du von GitHub installiert hast, hattest Du aber nicht :-( So kommen wir nur bedingt bis nicht weiter

**Comment by daniel-lo** [comment]
Hab bis jetzt alles befolgt .. aber kann sein, dass durch den Rollback wieder was verloren genagen ist. So wie die Meldung jetzt kommt .. ist sie zu schnell wieder weg um was zu drücken. Ich installiere jetzt von Git und mache dann morgen weiter .. dann ist die Git-Version im Backup

Kann doch auch nichts dafür, dass mein Iobroker durch installationen unbrauchbar wird.

**Comment by daniel-lo** [comment]
token aktualisiert jetzt wieder .. danke .. das Popup kommt noch immer .. aber ich köntne auch anklicken nicht wieder anzeigen und den Fehler ingnorieren .. wenn die checkbox greift.

**Comment by daniel-lo** [comment]
Checkbox gibt es erst beim zweiten erscheinen .. also nicht beim öffnen der config sondern nach der token aktualisierung .. traue mich auch nicht das anzuhaken .. der Text liest sich so also könnte es sich auch negativ auswirken:

![grafik](https://user-images.githubusercontent.com/4311558/158776448-e2733835-13c3-444a-a00f-693812bae11c.png)
