### ISSUE TITLE
Warn & Error

### ISSUE THREAD

**Issue by Negalein** [iobroker-community-adapters/ioBroker.fitbit-api#28]
Bekomme folgende Meldungen

`fitbit-api.0 | 2021-09-01 23:30:02.264 | warn | setObject calories (type=state) property common.role missing!`
`fitbit-api.0 | 2021-09-01 23:30:02.258 | warn | setObject restingHeartRate (type=state) property common.role missing!`
`fitbit-api.0 | 2021-09-01 23:30:02.256 | error | Cannot read: fat is not found`
`fitbit-api.0 | 2021-09-01 23:30:02.251 | warn | setObject steps (type=state) property common.role missing!`

**Comment by Apollon77** [comment]
should be fixed in next version
