### ISSUE TITLE
fitbit login page won't load in frame

### ISSUE THREAD

**Issue by Garfonso** [iobroker-community-adapters/ioBroker.fitbit-api#5]
fitbit login page won't load in frame (anymore?).

![fitbit-error-firefox](https://user-images.githubusercontent.com/620860/83693282-18830900-a5f6-11ea-9c6f-8bbd19bca65b.JPG)

//Edit:
if you are already logged in to fitbit in the same browser (i.e. cookies are there) then the page loads. This seems the only way to log in currently.

**Comment by MK-2001** [comment]
You can generate the access token there: https://dev.fitbit.com/apps/oauthinteractivetutorial

**Comment by Apollon77** [comment]
Then we need to open a popup window instead iframe? Can you do a PR?

**Comment by Apollon77** [comment]
With current GitHub version it works at least in Firefox ...  but chrome still blocks it ... needs to be adjusted to not use IFrame

**Comment by SamLowrie** [comment]
It now doesn't work in FF as-well.

Also the fields for manually entering the credentials are read-only now (probably because of new admin versions). 

So for me this adapter doest work at all in the moment. Any chance to get it back to work?

**Comment by Apollon77** [comment]
Please try https://github.com/Chris-1965/ioBroker.fitbit-fitness ... this daoter will soon be replaced by tghis one
